### ISSUE TITLE
Create CDK deployment constructs and a basic demo stack for self-hosted Restate on AWS

### ISSUE THREAD

**Issue by pcholakov** [restatedev/cdk#1]
As part of our positioning for Restate within the AWS Serverless community, we want native-feeling CDK support for deploying Restate services. Additionally, we can provide an easy ramp for deploying self-hosted Restate on AWS using the same mechanism. This issue tracks the minimal requirements for a Restate CDK construct library that supports the following:

- Easily deploy Restate to AWS in a native, low-cost way that is suitable for dev/test and evaluation purposes; it should provide reasonable durability but no effort is made to ensure high availability
- Makes a basic effort to assist customers with operating the Restate infrastructure (e.g. sets up instance OS patching out of the box)
- Supports deploying AWS Lambda-based Restate services as easily as managing any other Lambda function in CDK
- The initial version will only support TypeScript

```[tasklist]
### Tasks
- [x] Create a basic EC2/VPC deployment for Restate
- [x] Send Restate logs to CloudWatch Logs
- [x] Create CDK Construct to deploy Restate on an EC2 instance
- [x] Create CDK Construct to deploy Lambda-based Restate services
- [ ] https://github.com/restatedev/restate-cdk-support/issues/3
- [ ] https://github.com/restatedev/restate-cdk-support/issues/2
- [ ] https://github.com/restatedev/restate-cdk-support/issues/4
- [ ] https://github.com/restatedev/restate-cdk-support/issues/5
- [x] Document the local dev experience story
- [ ] https://github.com/restatedev/restate-cdk-support/issues/9
- [ ] https://github.com/restatedev/restate-cdk-support/issues/8
- [ ] https://github.com/restatedev/restate-cdk-support/issues/7
- [x] Write announcement blog post for CDK/self-hosted Restate how-to
```
