### ISSUE TITLE
Implement deregistration of services from Restate

### ISSUE THREAD

**Issue by pcholakov** [restatedev/cdk#5]
Fix several known issues in `register-service-handler.ts` as of 2023-11-20.

The registration response looks like this:

```
% curl -X POST http://localhost:9070/endpoints -H 'content-type: application/json' -d '{"arn": "arn:aws:lambda:eu-central-1:663487780041:function:pavel-RestateStack-GreeterA41DC22A-o8knTdFWTHtj:3"}' -m 3
{"id":"YXJuOmF3czpsYW1iZGE6ZXUtY2VudHJhbC0xOjY2MzQ4Nzc4MDA0MTpmdW5jdGlvbjpwYXZlbC1SZXN0YXRlU3RhY2stR3JlZXRlckE0MURDMjJBLW84a25UZEZXVEh0ajoz","services":[{"name":"Greeter","revision":1}]}
```

```[tasklist]
### Tasks
- [ ] Handle CloudFormation `Delete` commands - deregister services from Restate
- [x] Add more robust retry and timeout handling to both health check and registration calls
- [x] Validate the endpoint registration response, return (some) output to CFn
```
